VolunteerManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from Volunteer import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required 
from registration.backends import simple

urlpatterns = patterns('',
    url(r'^', include('favicon.urls')),
    url(r'^admin/', include(admin.site.urls)),

    #url(r'^initialize/', views.initialize),
    #url(r'^passupdate/', views.passwordmassupdate),

    
    #Team Leads
    url(r'^team/$', views.team_choose),
    url(r'^team/(?P<team_arg>\d{1,})/$', views.team_view),
    url(r'^team/(?P<team_arg>\d{1,})/suggest/$', views.suggest_view),
    url(r'^team/(?P<team_arg>\d{1,})/email/$', views.email_view),
    url(r'^team/(?P<team_arg>\d{1,})/volunteers/$', views.unclaimed_list, name='team_unclaimed_list'),
    url(r'^team/(?P<team_arg>\d{1,})/volunteers/(?P<vol_arg>\d{1,})/$', views.volunteer_detail_view, name='team_volunteer_detail'),
    url(r'^team/(?P<team_arg>\d{1,})/availability/$', views.availability),
    url(r'^team/(?P<team_arg>\d{1,})/interested/$', views.interest_view),
    
    url(r'^team/volunteers/$', views.unclaimed_list, name='unclaimed_list'),
    url(r'^team/volunteers/(?P<vol_arg>\d{1,})/$', views.volunteer_detail_view, name='volunteer_detail'),
    url(r'^team/login/$', 'django.contrib.auth.views.login', { 'template_name': 'team_login.html'}),

    
    #Volunteer Profiles
    url(r'^home/$', login_required(views.home)),
    url(r'^profile/$', login_required(views.volunteer_create)),
    url(r'^ratings/$', login_required(views.rating)),
    url(r'^password/$', auth_views.password_change),
    

    #Registration
    url(r'^accounts/register/complete/$', views.volunteer_create),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^$', 'django.contrib.auth.views.login',  {'template_name': 'Volunteer/registration/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),



    #Password setting urls with built-in templates
    url(r'^password/change/$', auth_views.password_change, name='auth_password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='password_change_done'),
    #url(r'^password/reset/$', auth_views.password_reset, name='auth_password_reset'),
    #url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='auth_password_reset_confirm'),
    #url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    #url(r'^password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
)

Volunteer/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

#Team describes a Department
class Team(models.Model):
    #Budget =  Number of team members allowed
    budget = models.PositiveSmallIntegerField(default=0)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500, blank=True)
    visible = models.BooleanField(default= True)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return "/team/%s" % (self.id)
        
    def get_available(self):
        return self.budget - Volunteer.objects.filter(team=self)

#The Volunteer class contains basic information about the Volunteer. OneToOneField relationship to the user.     
class Volunteer(models.Model):
    class Meta:
        ordering = ['first_name']
        
    #CONSTANTS
    DIET_CHOICES = (
        ('Omnivore', "Omnivore - I like everything including Meat"),
        ('Vegetarian', "Vegetarian - I don't eat any meat"),
        ('Vegan', "Vegan - I don't eat any animal products!"),
    )
    PUBLIC_FIELD_NAMES = [ 'first_name', 'last_name' , 'email', 'playa_name', 'birthdate', 'phone', 'emergency_contact', 'emergency_phone',
        'FB_user_name', 'diet', 'diet_restriction', 'disability', 'attended_BM', 'v_YOUtopia', 'vexp_YOUtopia', 'v_other', 'vexp_other', 'super_powers', 'jokes', 'ass']
    
    AVAILABILITY_FIELD_NAMES = ['avail_tu','avail_w' ,'avail_th', 'avail_f','avail_sa' ,'avail_su', 'avail_m']
    PHONE_REGEX = RegexValidator(regex=r'^\d{3}-\d{3}-\d{4}x?\d{0,5}$', message="Phone number must be entered in the format: '999-999-9999' or '999-999-9999x123'. ")
    
    user = models.OneToOneField(User, related_name="profile", null=True)
    
    #User input fields
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=200)
    playa_name = models.CharField(max_length=30, blank=True)
    birthdate = models.DateField('Birth Date', help_text="mm/dd/yyyy")
    phone = models.CharField(max_length=20, validators=[PHONE_REGEX], help_text="'999-999-9999'") 
    emergency_contact = models.CharField(max_length=30)
    emergency_phone = models.CharField(max_length=20, validators=[PHONE_REGEX], help_text="'999-999-999'") 
    FB_user_name = models.CharField('Facebook User Name', max_length=30, blank=True, help_text='(http://www.facebook.com/--->USER NAME<--)')
    diet = models.CharField('Dietary Preference', max_length=30, choices = DIET_CHOICES, default='Omnivore', help_text='Please choose the answer that *best* fits your dietary lifestyle.')
    diet_restriction = models.CharField('Specific dietary restriction', max_length=254, blank=True, 
                                        help_text="Please list any food allergies. We encourage everyone to practice Radical Self-Reliance and provide food for themselves as we cannot guarantee our ability to accommodate everyone's dietary needs.")
    disability = models.CharField('Do you have any health or disability issues we should be aware of?', max_length=254, blank=True)
    attended_BM = models.BooleanField('Have you attended a Burning Man event before?', default=False)
    v_YOUtopia = models.BooleanField('Have you volunteered with YOUtopia before?', default=False)
    vexp_YOUtopia = models.CharField('If YES, which teams have you worked with?', max_length=254, blank=True)
    v_other = models.BooleanField('Have you volunteered with any other festivals or events before? ', default=False)
    vexp_other = models.CharField('If YES, please specify.', max_length=254, blank = True)
    super_powers = models.CharField('Super Powers', max_length=254, blank = True, help_text = "What special super powers or skills you have? What skills would you like to learn more about?")
    jokes = models.CharField('Questions? Comments? Favorite Joke?', max_length=254, blank = True, help_text="How do you kill a circus? Go for the juggler.")
    ass = models.BooleanField('Super Volunteer', default=False, blank=True,  help_text="Some teams will be choosing the most dedicated, experienced volunteers to train as assistants to the leads. These super volunteers will receive more training and more responsibility. Not everyone is cut out for this position, but we're looking for the best of the best.")

    #Availabiliity
    avail_tu = models.BooleanField('Tuesday, October 13th',default=True, blank=True)
    avail_w = models.BooleanField('Wednesday, October 14st', default=True, blank=True)
    avail_th = models.BooleanField('Thursday, October 15nd', default=True, blank=True)
    avail_f = models.BooleanField('Friday, October 16th', default=True, blank=True)
    avail_sa = models.BooleanField('Saturday, October 17th', default=True, blank=True)
    avail_su = models.BooleanField('Sunday, October 18th', default=True, blank=True)
    avail_m = models.BooleanField('Monday, October 19th', default=True, blank=True)
    
    #Team Choices
    approved = models.BooleanField('Have you already been selected to be part of a team?', default=False,  help_text="Some department heads are recruiting team members in advance. If you haven't already been recruited, not to fret! We will help place you on a team that fits your skills and interests.", blank= True)

    approved_by = models.CharField(max_length=30, blank=True)
    suggested_team = models.ForeignKey('Team', null=True, related_name = 'suggested_team', blank=True)
    team = models.ForeignKey('Team', blank= True, null=True, related_name='team')
    ratings = models.ManyToManyField(Team, through='Rating', related_name='ratings')
    
    #These fields are for administrative use.
    has_ticket = models.BooleanField(default=False)
    scheduled = models.BooleanField(default=False)
    volunteer_rating = models.PositiveSmallIntegerField(null=True) 

    notes = models.CharField(max_length=254, blank=True) 
    limbo = models.BooleanField(default=False)
        
    #Methods
    def __str__(self):
        return self.first_name + " " + self.last_name

        
    def get_absolute_url(self):
        return  '/team/volunteers/' + str(self.id)


class Rating(models.Model):
    class Meta:
        ordering = ['-rating']
    RATING_CHOICES = tuple((x, x) for x in range(1,6))
    volunteer = models.ForeignKey(Volunteer)
    team = models.ForeignKey(Team)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, default=1)
    
    def __str__(self):
        return self.team.name + ": " + str(self.rating)
    

Volunteer/forms.py
from django import forms
from Volunteer.models import *
from django.template.defaultfilters import mark_safe
from django.forms.models import modelformset_factory, inlineformset_factory
from django.forms.formsets import formset_factory


class HorizRadioRenderer(forms.RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self])+'<br>')
            


class VolunteerNotesForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = ['notes']

class VolunteerForm(forms.ModelForm):
    diet_restriction = forms.CharField(max_length=30, label='Specific dietary restriction:',  required=False,
                                        help_text=mark_safe("Please list any food allergies. <br>We encourage everyone to practice Radical Self-Reliance and provide food for themselves as we cannot guarantee our ability to accommodate everyone's dietary needs."))
    vexp_YOUtopia = forms.CharField(label=mark_safe('If so, which teams have you worked with?'), widget=forms.Textarea, required=False)
    vexp_other = forms.CharField(label=mark_safe('If so, please specify.'), widget=forms.Textarea, required=False)
    super_powers = forms.CharField(label=mark_safe('What special super powers or skills you have? What skills would you like to learn more about?'), widget=forms.Textarea, required=False)
    jokes = forms.CharField(label=mark_safe('Questions? Comments? Favorite Joke?'), widget=forms.Textarea, required=False, help_text="How do you kill a circus? Go for the juggler.")
    ass = forms.BooleanField(label ='Are you interested in taking on more responsibility than most volunteers to make your department run smoothly and YOUtopia better than ever?', required=False,  help_text="Some teams will be choosing the most dedicated, experienced volunteers to train as assistants to the leads. These super volunteers will receive more training and more responsibility. Not everyone is cut out for this position, but we're looking for the best of the best.")
    

    class Meta:
        model = Volunteer
        fields = Volunteer.PUBLIC_FIELD_NAMES + Volunteer.AVAILABILITY_FIELD_NAMES
        exclude = ['email']
        
        
class VolunteerSuggestForm(forms.ModelForm):
    #suggested_team = forms.ModelChoiceField(label="Suggested Team", required = False, queryset= Team.objects.all(), to_field_name="name")
    #notes = forms.CharField(max_length=30, label='Notes',  required=False)
    class Meta:
        model = Volunteer
        fields = [ 'first_name', 'last_name' ,  'playa_name', 'suggested_team', 'limbo', 'notes', 'birthdate',
                  'FB_user_name',  'disability', 'attended_BM', 'v_YOUtopia', 'vexp_YOUtopia', 
                  'v_other', 'vexp_other', 'super_powers', 'jokes', 'ass'] + Volunteer.AVAILABILITY_FIELD_NAMES 
        

        
    
class ReadOnlyFieldsMixin(object):
    readonly_fields =()

    def __init__(self, *args, **kwargs):
        super(ReadOnlyFieldsMixin, self).__init__(*args, **kwargs)
        for field in (field for name, field in self.fields.iteritems() if name in self.readonly_fields):
            field.widget.attrs['disabled'] = 'true'
            field.required = False
            
        for field in (field for name, field in self.fields.iteritems()):
            field.required = False

    def clean(self):
        cleaned_data = super(ReadOnlyFieldsMixin,self).clean()
        for field in self.readonly_fields:
           cleaned_data[field] = getattr(self.instance, field)

        return cleaned_data
        
class ReadOnlyVolunteerSuggestForm(ReadOnlyFieldsMixin, VolunteerSuggestForm):
    readonly_fields = Volunteer.PUBLIC_FIELD_NAMES + Volunteer.AVAILABILITY_FIELD_NAMES 
    


class RatingsForm(forms.Form):
    approved = forms.BooleanField(label='Are you a returning volunteer or have you already been selected to be part of a team?', 
                                  required = False, 
                                  help_text="Some department heads are recruiting team members in advance. If you haven't already been recruited, not to fret! We will help place you on a team that fits your skills and interests.")

    approved_team = forms.ModelChoiceField(label="Please select the team you've been recruited for", required = False, queryset= Team.objects.filter(visible=True), to_field_name="name")

    approved_by = forms.CharField(label='Which department head approved you?', max_length=30, required = False, help_text="Put (Returning) if you worked with this team last year.")
    
    def __init__(self, *args, **kwargs):
        teams = kwargs.pop('teams')
        super(RatingsForm, self).__init__(*args, **kwargs)

        for team in teams:
            self.fields[team.name] = forms.ChoiceField(label=team.name, 
                                                       help_text=team.description, 
                                                       choices=tuple((x, x) for x in range(1,6)), 
                                                       widget=forms.RadioSelect(renderer=HorizRadioRenderer))
RatingsFormSet= modelformset_factory

class VolunteerOfficeForm(forms.ModelForm):
    vexp_YOUtopia = forms.CharField(widget=forms.Textarea)
    vexp_other = forms.CharField(widget=forms.Textarea)
    super_powers = forms.CharField(widget=forms.Textarea)
    jokes = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Volunteer
        fields = '__all__'
        exclude = ['user', 'ratings']
        
class ReadOnlyVolunteerForm (ReadOnlyFieldsMixin, VolunteerOfficeForm):
    readonly_fields = Volunteer.PUBLIC_FIELD_NAMES + Volunteer.AVAILABILITY_FIELD_NAMES + ['approved','approved_by']
    
#RatingsFormSet = inlineformset_factory(Team, Rating, extra=0)
VolunteerFormSet = modelformset_factory(Volunteer, form=ReadOnlyVolunteerSuggestForm, extra = 0)

class VolunteerMiniForm(forms.ModelForm):
    class Meta:
        model= Volunteer
        fields = ['suggested_team','team', 'has_ticket','scheduled','volunteer_rating','notes','limbo'] 
        
    def __init__(self, *args, **kwargs):
        super(VolunteerMiniForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.iteritems():
            field.required = False
'''
class SuggestForm(forms.Form):
    def __init__(self, *args, **kwargs):
        volunteers = kwargs.pop('volunteers')
        super(SuggestForm, self).__init__()
        
        for volunteer in volunteers:
            self.fields[volunteer.id] = forms.ModelChoiceField(label=volunteer.first_name + volunteer.last_name,
                                                          queryset= Team.objects.all(), to_field_name="name",
                                                          required=False)
                                                          
'''                                                          

Volunteer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


{% load staticfiles %}
{% block stylesheet %} <link rel="stylesheet" type="text/css" href="{% static 'Volunteer/style.css' %}" /> {% endblock %}
<title>{% block title %}YOUtopia Volunteer Management{% endblock %}</title>

{%block script %} {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 s
	Support of HTML5 elements and media queries -->

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% block body %}
<div class="container-fluid" >
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}<a href="http://www.sdyoutopia.com"><img class="img-rounded img-responsive" src="{% static 'Volunteer/images/logo.jpg' %}"></img></a>{% endblock %}
        </div>
    </div>
    <!-- END Header -->
    
    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}<h1>YOUtopia 2015 Volunteer Application</h1>{% endblock %}
        {% block content %}{% endblock %}
        {% block sidebar %}{% endblock %}
		{% block postcontent %} {% endblock%}
        <br class="clear" />
    </div>
    <!-- END Content -->
    
     {% block footer %}<div id="footer"></div>{% endblock %}   
</div>
{% endblock %}
</body>

</html>

Volunteer/templates/home.html
{% extends "base.html" %}

{% block content_title %}
<h1>Success!!</h1>
<h3>Your Application has been submitted!</h3>
{% endblock %}

{% block content %}
 
 <p><h2>{{ volunteer.first_name }} {{ volunteer.last_name }} </h2></p>
 <p>Thank you, 
 
 {% if volunteer.playa_name %} 
	{{ volunteer.playa_name }}
{% else %} 
	{{volunteer.first_name }}
{% endif %}	
	! The YOUtopia team will now perform complex mathematical calculations to ensure your unique talents are matched up with an awesome team of super heroes.</p>

 <p>Please join us in the <a href="https://www.facebook.com/groups/youtopia.volunteers/">YOUtopia Volunteers Facebook group</a>. If you have any questions email us any time at volunteer@sdyoutopia.com.

 <ul>
	<li>username: {{ volunteer.user.username }}
    <li>email: {{ volunteer.email }}
    <li>Playa Name: {{ volunteer.playa_name }}
    <li>Birthdate: {{ volunteer.birthdate }}
    <li>Phone Number: {{ volunteer.phone }}
    <li>Emergency Contact: {{ volunteer.emergency_contact }}
    <li>Emergency Phone Number: {{ volunteer.emergency_phone }}
    <li>Facebook User Name: {{ volunteer.FB_user_name }}
    <li>Dietary Preference: {{ volunteer.get_diet_display  }}
    <li>Specific dietary restriction: {{ volunteer.diet_restriction }}
    <li>Health or disability issues: {{ volunteer.disability  }}
    <li>Have you attended a Burning Man event before? {{ volunteer.attended_BM }}
    <li>Have you volunteered with YOUtopia before? {{ volunteer.v_YOUtopia }}
    <li>If YES, which teams have you worked with? {{ volunteer.vexp_YOUtopia }}
    <li>Have you volunteered with any other festivals or events before? {{ volunteer.v_other }}
    <li>If YES, please specify. {{ volunteer.vexp_other }}
    <li>Super Powers: {{ volunteer.super_powers }}
    <li>Questions? Comments? Favorite Joke?: {{ volunteer.jokes }}
</ul>

<a href="/accounts/register/complete/">Update Information</a><br>
<a href="/ratings/">Rate Teams</a><br>
<a href="/logout/">Log Out</a>
{% endblock %}

Volunteer/templates/info.html
<ul>
	{% if volunteer.ass %} <li>This Volunteer has requested extra responsibility.</li>{%endif%}
	<li><h4>Birthdate:</h4> {{ volunteer.birthdate }} </li>
	<li><h4>Disability:</h4> {{ volunteer.disability  }} </li>
	<li><h4>Attended a Burning Man event before?</h4> {{ volunteer.attended_BM }}</li>
	{% if  volunteer.v_YOUtopia %} <li> <h4>YOUtopia Experience:</h4> </li> <p>{{volunteer.vexp_YOUtopia}} </p>{% endif %}
	{% if volunteer.v_other %} <li> <h4>Other Festival Experience:</h4> </li> <p> {{volunteer.vexp_other}} </p>{% endif %}
	<li><h4>Super Powers:</h4></li><p> {{ volunteer.super_powers }} </p>
	<li><h4>Comments:</h4> {{ volunteer.jokes }}</li>
	<li><h4>Notes:</h4> {{ volunteer.notes }} </li>
	{% if volunteer.avail_tu %}<li>Available Tuesday, October 13th {% endif %}</li>
	{% if volunteer.avail_w %}<li>Available Wednesday, October 14th {% endif %}</li>
	{% if volunteer.avail_th %}<li>Available Thursday, October 15th {% endif %}</li>
	{% if volunteer.avail_f %}<li>Available Friday, October 16th {% endif %}</li>
	{% if volunteer.avail_sa %}<li>Available Saturday, October 17th {% endif %}</li>
	{% if volunteer.avail_su %}<li>Available Sunday, October 18th {% endif %}</li>
	{% if volunteer.avail_m %}<li>Available Monday, October 19th {% endif %}</li>
	<li>Ratings:
		<ul>
		{% for rating in volunteer.rating_set.all %}
			<li>{{rating.team}} {{rating.rating}}</li>
			{% empty %}
			<li> No team ratings </li>
			{% endfor %}
		</ul></li>
		
</ul></li>

Volunteer/templates/interested_list.html
{% extends "unclaimed_list.html" %}

{% block content_title %} <h1>Volunteers Interested in {{this_team}}</h1> {% endblock %}

Volunteer/templates/unclaimed_list.html
{% extends "staffbase.html" %}

{% block content_title %} <h1>Unclaimed Volunteer List</h1> {% endblock %}

{% block content %}
<ul>
	<form method="POST" >{% csrf_token %}
{% for volunteer in volunteer_list %}
	<h3>{% include "volunteer_name.html" %}</h3>
	{% include "volunteer_info.html" %}
{% empty %}
    <li>No volunteers yet.</li>
{% endfor %}
</ul>

</form> 



{% endblock %}

Volunteer/templates/volunteer_form.html
{% extends "base.html" %}
{% block script %}

<script>
$(document).ready(function() {
	$('.vexp_YOUtopia').hide();
	$('.vexp_other').hide();
	
	$('#id_v_YOUtopia').change(function () {	
		$('.vexp_YOUtopia').toggle();
	});
	$('#id_v_other').change(function () {	
		$('.vexp_other').toggle();
	});
});
</script>

{% endblock %}
{% block content %}
<p>Thank you very much for your interest in volunteering for YOUtopia 2015! Our mutual participation as volunteers helps make YOUtopia the magical place it is. EVERYONE who attends YOUtopia volunteers in some way, whether by assisting their theme camp, helping fellow participants, building art, or contributing their talents to the event. </p>

<p>All participants are encouraged to come by the volunteer headquarters at the V Spot at any time to find a team of superheroes who need your help, but please submit this application *only* if you are confident in your ability to commit to volunteering your helping hands and heart for the specific teams designated below for a total of between 16-20 hours.</p> 

<p>If you cannot commit to 16-20 hours of being incredibly awesome, please swing through the V Spot on site whenever you are able, contact us at volunteer@sdyoutopia.com, join us in the YOUtopia Volunteers Facebook group, or talk to a department head directly to find the best fit for your amazing talents. </p>

<form action="" method="post">{% csrf_token %}
	{{ form.non_field_errors }}
   {% for field in form|slice:":18" %}
    <div class="{{field.html_name}}{% if field.errors %} FieldError{%endif%}">
        {{ field.errors }}
		{% if field.name == 'vexp_YOUtopia' %}{{ field.label_tag }}<br> {{ field }}  <br>{{ field.help_text }}
		{% elif field.name == 'vexp_other' %}{{ field.label_tag }}<br> {{ field }}  <br>{{ field.help_text }}
		{% elif field.name == 'super_powers' %}{{ field.label_tag }}<br> {{ field }}  <br>{{ field.help_text }}
		{% elif field.name == 'jokes' %}{{ field.label_tag }}<br> {{ field }}  <br>{{ field.help_text }}
		{% elif field.name == 'ass' %}{{ field }}{{ field.label_tag }}   <br>{{ field.help_text }}
        {% else %} {{ field.label_tag }} {{ field }}  {{ field.help_text }}
		{% endif %}
    </div>
{% endfor %}

<h3>Super Volunteers</h3>
	{% for field in form|slice:"18:19" %}
    <div class="{{field.html_name}}{% if field.errors %} FieldError{%endif%}">
        {{ field.errors }}

        {{ field }}{{ field.label_tag }}<br>{{ field.help_text }}


    </div>
{% endfor %}
<h3>Availability</h3>
<p>All volunteers will be required to work at least two days during the event (Thurs-Sun) unless prior arrangements have been made with your department head. Greater availability will directly affect your chance to be selected for a volunteer position.</p>


   {% for field in form|slice:"19:" %}
    <div class="{{field.html_name}}">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}  {{ field.help_text }}
    </div>
{% endfor %}
    <button type="submit" class="btn btn-primary">Next</button>
	Please continue to the next page to rate your desired teams.
</form>

{% endblock %} 

Volunteer/templates/volunteer_info.html
<ul>
	{% if volunteer.ass %} <li>This Volunteer has requested extra responsibility.</li>{%endif%}
	<li><h4>Birthdate:</h4> {{ volunteer.birthdate }} </li>
	<li><h4>Disability:</h4> {{ volunteer.disability  }} </li>
	<li><h4>Attended a Burning Man event before?</h4> {{ volunteer.attended_BM }}</li>
	{% if  volunteer.v_YOUtopia %} <li> <h4>YOUtopia Experience:</h4> </li> <p>{{volunteer.vexp_YOUtopia}} </p>{% endif %}
	{% if volunteer.v_other %} <li> <h4>Other Festival Experience:</h4> </li> <p> {{volunteer.vexp_other}} </p>{% endif %}
	<li><h4>Super Powers:</h4></li><p> {{ volunteer.super_powers }} </p>
	<li><h4>Comments:</h4> {{ volunteer.jokes }}</li>
	<li><h4>Notes:</h4> {{ volunteer.notes }} </li>
	{% if volunteer.avail_tu %}<li>Available Tuesday, October 13th {% endif %}</li>
	{% if volunteer.avail_w %}<li>Available Wednesday, October 14th {% endif %}</li>
	{% if volunteer.avail_th %}<li>Available Thursday, October 15th {% endif %}</li>
	{% if volunteer.avail_f %}<li>Available Friday, October 16th {% endif %}</li>
	{% if volunteer.avail_sa %}<li>Available Saturday, October 17th {% endif %}</li>
	{% if volunteer.avail_su %}<li>Available Sunday, October 18th {% endif %}</li>
	{% if volunteer.avail_m %}<li>Available Monday, October 19th {% endif %}</li>
	<li>Ratings:
		<ul>
		{% for rating in volunteer.rating_set.all %}
			<li>{{rating.team}} {{rating.rating}}</li>
			{% empty %}
			<li> No team ratings </li>
			{% endfor %}
		</ul></li>
		
</ul></li>